AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless MDM Resources Stack

Parameters:
  AppCode:
    Type: String
    Default: FP197
  AppCodeLower:
    Type: String
    Default: fp197
  AppName:
    Type: String
    Default: mdm
  TeamName:
    Type: String
    Default: read-army
  Region:
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
    Default: us-east-1
  Department:
    Type: String
    Default: "Customer Service IT"
  OwnerContact:
    Type: String
    Default: "nicolas.zerrate@fpl.com"
  RolePermissionBoundary:
    Type: String
Mappings:
  AccountIDMap:
    "237980099910":
      VPCShortName: FPLSandbox
      VPCShortNameLower: fplsandbox
    "977465404123":
      VPCShortName: FPLDev
      VPCShortNameLower: fpldev
    "516627182506":
      VPCShortName: FPLTest
      VPCShortNameLower: fpltest
      SFTPHostName: "b2btest-int.nee.com"
    "485449107334":
      VPCShortName: FPLQA
      VPCShortNameLower: fplqa
      SFTPHostName: "b2bqa-int.nee.com"
    "430004966399":
      VPCShortName: FPLProd
      VPCShortNameLower: fplprod
      SFTPHostName: "b2b-int.nee.com"
    "202055847252":
      VPCShortName: FPLDR
      VPCShortNameLower: fpldr
Resources:
  RDSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 
        Fn::Sub:
          - 2${AccountCodeLower}${Region}-${AppCodeLower}-${AppName}-RDS-Secret
          - AccountCodeLower: !ImportValue Account-Global-AccountCodeLower
            Region:
              Fn::ImportValue: !Sub "Account-Global-RegionCodeLower-${AWS::Region}"
      Description: MDM Application RDS Secret
      SecretString: '{"username":"mdm_app_owner","password":"mdm_app_owner123"}'
      Tags:
        - Key: AppCode
          Value: !Sub ${AppCode}
        - Key: AppName
          Value: !Sub ${AppName}
  RDSProxy:
    Type: AWS::RDS::DBProxy
    Properties: 
      Auth: 
        - {AuthScheme: SECRETS, SecretArn: !Ref RDSSecret, IAMAuth: DISABLED}
      DBProxyName:
        Fn::Sub:
          - aws-${AccountCodeLower}${Region}-${AppCodeLower}-${AppName}-RDS-Proxy
          - AccountCodeLower: !ImportValue Account-Global-AccountCodeLower
            Region:
              Fn::ImportValue: !Sub "Account-Global-RegionCodeLower-${AWS::Region}"
      DebugLogging: false
      EngineFamily: POSTGRESQL
      IdleClientTimeout: 1800 # 30 minutes
      RequireTLS: false
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/fp197-read-army-mdm-RDS-Role
      VpcSecurityGroupIds: 
        - Fn::ImportValue: !Sub "${AppCode}-RDS-Proxy-L4-SG"
      VpcSubnetIds: 
        - Fn::ImportValue:
            !Join ['-',[ 'VPC', !FindInMap [AccountIDMap, !Ref "AWS::AccountId", VPCShortName], 'A', 'DataBase', 'SUBNET' ] ]
        - Fn::ImportValue:
            !Join ['-',[ 'VPC', !FindInMap [AccountIDMap, !Ref "AWS::AccountId", VPCShortName], 'B', 'DataBase', 'SUBNET' ] ]
        - Fn::ImportValue:
            !Join ['-',[ 'VPC', !FindInMap [AccountIDMap, !Ref "AWS::AccountId", VPCShortName], 'C', 'DataBase', 'SUBNET' ] ]
      Tags:
        - Key: AppCode
          Value: !Sub ${AppCode}
        - Key: AppName
          Value: !Sub ${AppName}
  RDSProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties: 
      ConnectionPoolConfigurationInfo: 
        ConnectionBorrowTimeout: 120
        MaxConnectionsPercent: 100
        MaxIdleConnectionsPercent: 50
      DBClusterIdentifiers: 
        - Fn::Sub:
            - aws-${AccountCodeLower}${Region}-${AppCodeLower}-${AppName}-cluster01-rds
            - AccountCodeLower: !ImportValue Account-Global-AccountCodeLower
              Region:
                Fn::ImportValue: !Sub "Account-Global-RegionCodeLower-${AWS::Region}"
      DBProxyName: !Ref RDSProxy
      TargetGroupName: default
